=== itzmmohit/Lab_3/login_form.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="nirvana">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="title"/>
        <xs:element name="login" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="first"/>
              <xs:element type="xs:string" name="last"/>
              <xs:element type="xs:string" name="email"/>
              <xs:element type="xs:string" name="username"/>
              <xs:element type="xs:string" name="pass"/>
              <xs:element type="xs:string" name="cpass"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== itzmmohit/Lab_3/login_form.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="login_form.xsl" type="text/xsl"?>
<nirvana xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="login_form.xsd">
    <title>Nirvana Data</title>
    <login>
        <first>MOHIT</first>
        <last>MEHTA</last>
        <email>mmehta692@gmail.com</email>
        <username>itz_mhit</username>
        <pass>h9yaarekes</pass>
        <cpass>h9yaarekes</cpass>
    </login>
    <login>
        <first>KHUSHBU</first>
        <last>KUMARI</last>
        <email>kkmehta@gmail.com</email>
        <username>khushi</username>
        <pass>766754</pass>
        <cpass>766754</cpass>
    </login>
    <login>
        <first>MONIKA</first>
        <last>MEHTA</last>
        <email>monikamehta@gmail.com</email>
        <username>mona</username>
        <pass>84484654</pass>
        <cpass>84484654</cpass>
    </login>
    <login>
        <first>PRIYA</first>
        <last>MEHTA</last>
        <email>priya831001@gmail.com</email>
        <username>priyame_831</username>
        <pass>qwertyuiop</pass>
        <cpass>qwertyuiop</cpass>
    </login>
</nirvana>
